name: Tests

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  php-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.2, 8.1, 8.0]

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: pcov
        extensions: gd

    - name: Install dependencies
      run: |
        composer update --prefer-dist --no-interaction --no-progress

    - name: Execute Unit Tests
      run: composer test